#!/usr/bin/env node
// Builds the APK's embedded webroot from an upstream integration zip:
//
//   node tools/apk/build-webroot.mjs [--zip <path|url>] [--tag vX.Y.Z]
//
// Pipeline: fetch upstream zip → extract → copy the shell-relevant subset →
// copy tools/apk/extras (shell-owned files: dc-bridge.js, webrtc-bridge.mjs) →
// apply tools/apk/patches/*.json (settings, font scale, side pad, /_shell/rooms,
// dc-bridge import) → npm install werift (host-side WebRTC bridge, pure JS).
// A missing patch anchor fails the build loudly — patches are data, never silent.
import { execFileSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const UPSTREAM_API = 'https://api.github.com/repos/sganggs/Stronghold-Protocol/releases/latest';
const MIRROR_PREFIX = 'https://gh-proxy.com/';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..', '..');
const outDir = path.join(repo, 'android', 'app', 'src', 'main', 'assets', 'webroot');
const patchesDir = path.join(here, 'patches');
const extrasDir = path.join(here, 'extras');

async function main() {
  const argZip = process.argv.indexOf('--zip');
  let zipPath = argZip > 0 ? process.argv[argZip + 1] : null;
  let tag = argvValue('--tag');
  if (!zipPath) {
    const rel = await latestRelease();
    tag = tag ?? rel.tag;
    zipPath = path.resolve(repo, '..', 'dl-cache', `upstream-${rel.tag}.zip`);
    fs.mkdirSync(path.dirname(zipPath), { recursive: true });
    if (!fs.existsSync(zipPath) || fs.statSync(zipPath).size < 100_000_000) {
      await download(rel.zipUrl, zipPath).catch(async (e) => {
        console.warn(`direct download failed (${e.message}), trying mirror…`);
        await download(MIRROR_PREFIX + rel.zipUrl, zipPath);
      });
    }
  }
  console.log(`upstream zip: ${zipPath} (tag ${tag ?? 'unknown'})`);

  const staging = path.resolve(repo, '..', 'dl-cache', 'upstream-extracted');
  fs.rmSync(staging, { recursive: true, force: true });
  fs.mkdirSync(staging, { recursive: true });
  const zip = path.resolve(zipPath);
  if (process.platform === 'win32') execFileSync('C:/Windows/System32/tar.exe', ['-xf', zip, '-C', staging]);
  else execFileSync('unzip', ['-q', zip, '-d', staging]);

  const [srcRoot] = fs.readdirSync(staging).filter((n) => fs.statSync(path.join(staging, n)).isDirectory());
  const src = path.join(staging, srcRoot);
  if (!fs.existsSync(path.join(src, 'server', 'index.js'))) throw new Error(`unexpected zip layout under ${src}`);

  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  for (const name of fs.readdirSync(path.join(src, 'public'))) {
    if (name === 'dev') continue;
    fs.cpSync(path.join(src, 'public', name), path.join(outDir, name), { recursive: true });
  }
  for (const dir of ['data', 'shared', 'server', 'node_modules']) {
    fs.cpSync(path.join(src, dir), path.join(outDir, dir), { recursive: true });
  }
  fs.copyFileSync(path.join(src, 'package.json'), path.join(outDir, 'package.json'));
  fs.cpSync(path.join(src, 'server', 'sim'), path.join(outDir, 'sim'), { recursive: true });

  fs.writeFileSync(path.join(outDir, 'data.js'), `// Generated by server/index.js — browser stand-in for server/data.js (DESIGN §14 client-side combat).
// The simulation's content modules (/sim/content/support/index.js) import getData() from here; it returns the game data
// the page injected with /sim/simdata.js setSimData(data).
import { getSimData } from './sim/simdata.js';
export function getData() { return getSimData() || {}; }
export function resetData() {}
`);

  // shell-owned extras (over-write whatever upstream shipped at those paths)
  copyExtras();

  // shell patches (settings, dc-bridge wiring, /_shell/rooms)
  applyPatches(outDir);

  // werift for the host-side WebRTC bridge (pure JS, no native deps)
  console.log('installing werift…');
  execFileSync(process.platform === 'win32' ? 'npm.cmd' : 'npm',
    ['install', 'werift', '--no-save', '--no-audit', '--no-fund', '--loglevel=error'],
    { cwd: outDir, stdio: 'inherit', shell: process.platform === 'win32' });

  // version stamp for the device-side "skip re-materialising 433 MB" check (HostService.materialiseContent):
  // a content hash of (path, size) over the whole tree — identical trees materialise once, changed trees copy once.
  const stamp = contentStamp(outDir);
  fs.writeFileSync(path.join(outDir, '.stamp'), stamp + '\n');
  console.log(`webroot stamp: ${stamp}`);

  const size = dirSize(outDir);
  console.log(`webroot ready: ${outDir} (${(size / 1024 / 1024).toFixed(0)} MB)`);
}

function contentStamp(dir) {
  const h = crypto.createHash('sha256');
  const entries = [];
  (function walk(d, rel) {
    for (const e of fs.readdirSync(d, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const p = path.join(d, e.name);
      const r = rel ? `${rel}/${e.name}` : e.name;
      if (e.isDirectory()) walk(p, r);
      else entries.push(`${r}:${fs.statSync(p).size}`);
    }
  })(dir, '');
  for (const line of entries) h.update(line).update('\n');
  return h.digest('hex').slice(0, 24);
}

function copyExtras() {
  if (!fs.existsSync(extrasDir)) return;
  // extras/public/* mirrors the webroot ROOT (the interceptor serves /js/... from root);
  // extras/server/* mirrors webroot/server/*.
  const sides = [
    { from: path.join(extrasDir, 'public'), to: outDir, label: '' },
    { from: path.join(extrasDir, 'server'), to: path.join(outDir, 'server'), label: 'server/' },
  ];
  for (const side of sides) {
    if (!fs.existsSync(side.from)) continue;
    for (const p of walk(side.from)) {
      const rel = path.relative(side.from, p);
      const dst = path.join(side.to, rel);
      fs.mkdirSync(path.dirname(dst), { recursive: true });
      fs.copyFileSync(p, dst);
      console.log(`extra: ${side.label}${rel.split(path.sep).join('/')}`);
    }
  }
}

function applyPatches(outDir) {
  // deterministic order: settings-v2.1 → settings-v2.2 (later patches build on earlier text)
  for (const pf of fs.readdirSync(patchesDir).filter((n) => n.endsWith('.json')).sort()) {
    const spec = JSON.parse(fs.readFileSync(path.join(patchesDir, pf), 'utf-8'));
    for (const p of spec.patches) {
      const target = path.join(outDir, p.file);
      if (!fs.existsSync(target)) throw new Error(`patch target missing: ${p.file}`);
      const text = fs.readFileSync(target, 'utf-8');
      if (!text.includes(p.find)) {
        throw new Error(`patch anchor not found in ${p.file}: ${JSON.stringify(p.find.slice(0, 80))}`);
      }
      fs.writeFileSync(target, text.split(p.find).join(p.replace));
      console.log(`patched: ${p.file}`);
    }
  }
}

function* walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) yield* walk(p);
    else yield p;
  }
}

function argvValue(name) {
  const i = process.argv.indexOf(name);
  return i > 0 ? process.argv[i + 1] : null;
}

async function latestRelease() {
  const res = await fetch(UPSTREAM_API, { headers: { 'User-Agent': 'stronghold-shell' } });
  if (!res.ok) throw new Error(`upstream API HTTP ${res.status}`);
  const json = await res.json();
  const asset = (json.assets ?? []).find((a) => a.name.toLowerCase().endsWith('.zip'));
  if (!asset) throw new Error('upstream release has no zip asset');
  return { tag: json.tag_name, zipUrl: asset.browser_download_url };
}

async function download(url, dest) {
  console.log(`downloading ${url}`);
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  fs.writeFileSync(dest, buf);
  console.log(`saved ${(buf.length / 1024 / 1024).toFixed(1)} MB`);
}

function dirSize(dir) {
  let total = 0;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    total += e.isDirectory() ? dirSize(p) : fs.statSync(p).size;
  }
  return total;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
