#!/usr/bin/env node
// Builds the APK's embedded webroot from an upstream integration zip:
//
//   node tools/apk/build-webroot.mjs [--zip <path|url>] [--tag vX.Y.Z]
//
// Subset map (everything else is dropped):
//   <root>/public/**          → webroot/**      (minus public/dev)
//   <root>/data/**            → webroot/data/**
//   <root>/shared/**          → webroot/shared/**
//   <root>/server/**          → webroot/server/**
//   <root>/node_modules/**    → webroot/node_modules/**
//   <root>/package.json       → webroot/package.json
// The host server also needs webroot/sim (the browser stand-in mount), served from
// server/sim at runtime, so it is duplicated to webroot/sim.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const UPSTREAM_API = 'https://api.github.com/repos/sganggs/Stronghold-Protocol/releases/latest';
const MIRROR_PREFIX = 'https://gh-proxy.com/';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..', '..');
const outDir = path.join(repo, 'android', 'app', 'src', 'main', 'assets', 'webroot');

async function main() {
  const argZip = process.argv.indexOf('--zip');
  let zipPath = argZip > 0 ? process.argv[argZip + 1] : null;
  let tag = argvValue('--tag');
  if (!zipPath) {
    const rel = await latestRelease();
    tag = tag ?? rel.tag;
    zipPath = path.resolve(repo, '..', 'dl-cache', `upstream-${rel.tag}.zip`);
    fs.mkdirSync(path.dirname(zipPath), { recursive: true });
    if (!fs.existsSync(zipPath) || fs.statSync(zipPath).size < 100_000_000) {
      await download(rel.zipUrl, zipPath).catch(async (e) => {
        console.warn(`direct download failed (${e.message}), trying mirror…`);
        await download(MIRROR_PREFIX + rel.zipUrl, zipPath);
      });
    }
  }
  console.log(`upstream zip: ${zipPath} (tag ${tag ?? 'unknown'})`);

  const staging = path.resolve(repo, '..', 'dl-cache', 'upstream-extracted');
  fs.rmSync(staging, { recursive: true, force: true });
  fs.mkdirSync(staging, { recursive: true });
  const zip = path.resolve(zipPath);
  const isWin = process.platform === 'win32';
  if (isWin) execFileSync('C:/Windows/System32/tar.exe', ['-xf', zip, '-C', staging]);
  else execFileSync('unzip', ['-q', zip, '-d', staging]);

  // the zip carries a single top-level folder; find it instead of hardcoding
  const [srcRoot] = fs.readdirSync(staging)
    .filter((n) => fs.statSync(path.join(staging, n)).isDirectory());
  const src = path.join(staging, srcRoot);
  if (!fs.existsSync(path.join(src, 'server', 'index.js'))) {
    throw new Error(`unexpected zip layout under ${src}`);
  }

  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  // public/** → webroot/** (minus dev)
  for (const name of fs.readdirSync(path.join(src, 'public'))) {
    if (name === 'dev') continue;
    fs.cpSync(path.join(src, 'public', name), path.join(outDir, name), { recursive: true });
  }
  for (const dir of ['data', 'shared', 'server', 'node_modules']) {
    fs.cpSync(path.join(src, dir), path.join(outDir, dir), { recursive: true });
  }
  fs.copyFileSync(path.join(src, 'package.json'), path.join(outDir, 'package.json'));
  // browser stand-in mount /sim → server/sim (mirror of server/index.js DATA_SHIM_JS contract)
  fs.cpSync(path.join(src, 'server', 'sim'), path.join(outDir, 'sim'), { recursive: true });

  // generated /data.js shim (exact copy of the server's DATA_SHIM_JS contract)
  fs.writeFileSync(path.join(outDir, 'data.js'), `// Generated by server/index.js — browser stand-in for server/data.js (DESIGN §14 client-side combat).
// The simulation's content modules (/sim/content/support/index.js) import getData() from here; it returns the game data
// the page injected with /sim/simdata.js setSimData(data).
import { getSimData } from './sim/simdata.js';
export function getData() { return getSimData() || {}; }
export function resetData() {}
`);

  const size = dirSize(outDir);
  console.log(`webroot ready: ${outDir} (${(size / 1024 / 1024).toFixed(0)} MB)`);
}

function argvValue(name) {
  const i = process.argv.indexOf(name);
  return i > 0 ? process.argv[i + 1] : null;
}

async function latestRelease() {
  const res = await fetch(UPSTREAM_API, { headers: { 'User-Agent': 'stronghold-shell' } });
  if (!res.ok) throw new Error(`upstream API HTTP ${res.status}`);
  const json = await res.json();
  const asset = (json.assets ?? []).find((a) => a.name.toLowerCase().endsWith('.zip'));
  if (!asset) throw new Error('upstream release has no zip asset');
  return { tag: json.tag_name, zipUrl: asset.browser_download_url };
}

async function download(url, dest) {
  console.log(`downloading ${url}`);
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  fs.writeFileSync(dest, buf);
  console.log(`saved ${(buf.length / 1024 / 1024).toFixed(1)} MB`);
}

function dirSize(dir) {
  let total = 0;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    total += e.isDirectory() ? dirSize(p) : fs.statSync(p).size;
  }
  return total;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
