import test from 'node:test';
import assert from 'node:assert/strict';
import { ApplicationQueue } from '../../worker/rooms/applications.js';
test('approval cannot overbook, bypass the host, survive starting, or be reused by another account', () => {
  let now=1000;
  const q=new ApplicationQueue({now:()=>now});
  const room={hostId:'host',inMatch:false,freeSeats:1};
  const a=q.apply({accountId:'alice',name:'Alice'}), b=q.apply({accountId:'bob',name:'Bob'});
  assert.equal(q.apply({accountId:'alice',name:'Alice'}).id,a.id);
  assert.throws(()=>q.decide('stranger',a.id,'approved',room),/NOT_HOST/);
  const approved=q.decide('host',a.id,'approved',room);
  assert.throws(()=>q.decide('host',b.id,'approved',room),/ROOM_FULL/);
  assert.equal(q.consume('bob',approved.ticket),false);
  assert.equal(q.consume('alice',approved.ticket),true);
  assert.equal(q.consume('alice',approved.ticket),false);
  assert.throws(()=>q.decide('host',b.id,'approved',{...room,inMatch:true}),/ROOM_STARTED/);
  now+=120001;
  assert.equal(q.list().find(x=>x.id===b.id).status,'expired');
});
test('pending approvals and expiry persist; cancellation and invalidation release reservations', () => {
  let now=1000;
  const q=new ApplicationQueue({now:()=>now}), room={hostId:'host',inMatch:false,freeSeats:1};
  const a=q.apply({accountId:'alice',name:'Alice'});
  q.decide('host',a.id,'approved',room);
  const restored=new ApplicationQueue({snapshot:JSON.parse(JSON.stringify(q.snapshot())),now:()=>now});
  assert.equal(restored.reservedCount(),1);
  now+=30001;
  assert.equal(restored.reservedCount(),0);
  const b=restored.apply({accountId:'bob',name:'Bob'});restored.cancel('bob',b.id);
  assert.equal(restored.list().find(x=>x.id===b.id).status,'cancelled');
  const c=restored.apply({accountId:'charlie',name:'C'});restored.invalidate();
  assert.equal(restored.list().find(x=>x.id===c.id).status,'expired');
});
