// server/http/static.js — the static file server (routes.js hands it every GET / HEAD that is not an API route):
// (i18n-ignore-file: the error pages are bilingual by design, 中文 · English — docs/I18N.md)
//
//     /        → public/      (index.html for directories)
//     /data/   → data/        (generated game data)
//     /shared/ → shared/      (ESM shared with the browser)
//     /sim/    → server/sim/  (the battle simulation, read-only, `.js` only — client-side
//                              combat, DESIGN §14; the Node-only loader nodeData.js is not served)
//     /data.js → a generated browser stand-in of server/data.js (the sim's content modules
//                import `../../../data.js`; in the browser it serves the data injected with
//                /sim/simdata.js setSimData). No other server file is ever served.
//     /media/bgm/act1 → public/assets/audio/bgm/act1.mp3 — the same audio files, addressed
//                **without** an extension so download managers (IDM / 迅雷 …) stop popping a
//                "下载文件信息" dialog for every BGM track (media.js, shared/media.js, public/js/media.js)
//     /packs/index.json → the content packs of this server (server/packs.js: the language packs of
//                public/i18n/ and the pack folders of packs/, re-read when they change; never cached)
//     /packs/<id>/<file> → a file of a pack folder — only one its manifest names (server/packs.js servable)
//
// Traversal & dotfile protection, a directory without its trailing slash → 301, 404 page; an absent
// data/local-assets.json is answered with an empty manifest. Files go out through files.js serveFile.

import fsp from 'node:fs/promises';
import path from 'node:path';
import { gzip as gzipCb } from 'node:zlib';
import { promisify } from 'node:util';
import { MEDIA_PREFIX } from '../../shared/media.js';
import { ROOT, noopLog } from './config.js';
import { sendError, sendJson } from './common.js';
import { MIME, GZIP_MIN_BYTES, GzipCache, acceptsGzip, cacheControlFor, isNotModified, serveFile, servesVersionedModule } from './files.js';
import { versionModuleJs } from './moduleVersion.js';
import { serveMedia } from './media.js';
import { buildTag } from './buildTag.js';
import { createPackRegistry } from '../packs.js';
import { PACKS_URL, PACK_INDEX_FILE } from '../../shared/packs.js';

const gzipAsync = promisify(gzipCb);

/** Browser stand-in of server/data.js, served at /data.js (see the header). Served byte for byte: its first line names the entry, server/index.js. */
export const DATA_SHIM_JS = `// Generated by server/index.js — browser stand-in for server/data.js (DESIGN §14 client-side combat).
// The simulation's content modules (/sim/content/support/index.js) import getData() from here; it returns the game data
// the page injected with /sim/simdata.js setSimData(data).
import { getSimData } from './sim/simdata.js';
export function getData() { return getSimData() || {}; }
export function resetData() {}
`;
/** Files under server/sim that are never served (Node-only). */
const SIM_PRIVATE = new Set(['nodedata.js']); // lower-case (compared case-insensitively)

// ---------------------------------------------------------------------------------------------------
// Static file handler
// ---------------------------------------------------------------------------------------------------

/** Optional per-machine art manifest (tools/local-extract) and the empty stand-in served when it is absent. */
const LOCAL_ART_MANIFEST = 'local-assets.json';
const EMPTY_LOCAL_ART = Buffer.from(JSON.stringify({ version: 1, source: 'none', count: 0, groups: {} }));

/**
 * 素材 CDN (`SP_ASSET_CDN`, a deployment setting like HOST/PORT — empty = off, the default): the three art manifests
 * are answered with absolute `<base>assets/…` URLs, so browsers load the art from the CDN and this server carries no
 * art traffic (a 350 MB install costs the host nothing per player). Only the **response** is rewritten — server/data.js
 * and server/update.js keep reading the file on disk, and with the variable unset the body is byte-for-byte the file.
 * A value that is not an absolute http(s) URL is refused with a warning: an unusable base must never break a server
 * that can still serve its own art. Read once per handler (a change needs a restart).
 */
const CDN_ART_MANIFESTS = new Set(['assets.json', 'local-assets.json', 'emotes.json']);
/** `"path": "/assets/…` and `"/fonts/…` inside the manifests — the only things rewritten (the CDN hosts both trees). */
const ART_PATH_IN_JSON = /"\/(?:assets|fonts)\//g;

/** `SP_ASSET_CDN` normalized to `<origin><path>/` ('' when unset or unusable). */
function normalizeAssetCdn(raw, log) {
  const value = String(raw || '').trim();
  if (!value) return '';
  let u;
  try { u = new URL(value); } catch { log.warn(`[http] SP_ASSET_CDN is not an absolute URL, art stays local: ${value}`); return ''; }
  if (u.protocol !== 'http:' && u.protocol !== 'https:') { log.warn(`[http] SP_ASSET_CDN must be http(s), art stays local: ${value}`); return ''; }
  if (!u.pathname.endsWith('/')) u.pathname += '/';
  u.search = '';
  u.hash = '';
  return u.href;
}

/**
 * Answer one art manifest with its `/assets/…` paths pointed at the CDN. Mirrors serveFile's json handling (no-cache,
 * ETag + Last-Modified + 304, optional gzip); the rewritten body (and its gzip) is cached per file mtime + base.
 * @returns {Promise<boolean>} false when the file cannot be read (the caller falls back to serveFile)
 */
async function serveArtManifest(req, res, absPath, stat, base, log) {
  const key = `${absPath}\0${stat.size}\0${Math.floor(stat.mtimeMs)}\0${base}`;
  let entry = CACHE.get(key);
  if (!entry) {
    let raw;
    try { raw = await fsp.readFile(absPath, 'utf8'); } catch { return false; }
    entry = { body: Buffer.from(raw.replace(ART_PATH_IN_JSON, (m) => `"${base}${m.slice(2)}`), 'utf8'), gz: null };
    CACHE.clear(); // a manifest is ~1 MB; only the live file(s) are worth keeping
    CACHE.set(key, entry);
    log.info && log.info(`[http] art CDN: ${path.basename(absPath)} → ${base}{assets,fonts}/ (${(entry.body.length / 1e3).toFixed(0)} KB)`);
  }
  const useGzip = acceptsGzip(req.headers['accept-encoding']);
  const tag = `"cdn-${stat.size.toString(16)}-${Math.floor(stat.mtimeMs).toString(16)}${useGzip ? '-gz' : ''}"`;
  const headers = {
    'Content-Type': MIME['.json'],
    'Cache-Control': 'no-cache',
    ETag: tag,
    'Last-Modified': stat.mtime.toUTCString(),
    Vary: 'Accept-Encoding',
  };
  if (isNotModified(req, tag, stat.mtime)) { res.writeHead(304, headers); res.end(); return true; }
  let body = entry.body;
  if (useGzip) {
    if (!entry.gz) entry.gz = await gzipAsync(entry.body, { level: 6 });
    body = entry.gz;
    headers['Content-Encoding'] = 'gzip';
  }
  headers['Content-Length'] = body.length;
  res.writeHead(200, headers);
  res.end(req.method === 'HEAD' ? undefined : body);
  return true;
}
/** Rewritten-manifest cache (module scope: shared by handlers, keyed by path + mtime + CDN base). */
const CACHE = new Map();

// ---------------------------------------------------------------------------------------------------
// module graph: stamp the build tag onto the imports inside the served `.js` (moduleVersion.js)
// ---------------------------------------------------------------------------------------------------

// index.html is only the entry: the ~190 modules it leads to are what a returning player revalidates. With the
// specifiers stamped, `?v=` puts each one on the IMMUTABLE_CACHE branch (files.js) — the edge and the browser
// keep them for a year, and the host pays for the graph once per deploy instead of every four hours.
// Only the body is rewritten, in memory: the file on disk stays byte-for-byte what was shipped.
//
// The body (and its gzip) is cached per file mtime + tag, and the cache holds ONE build at a time: a deploy
// changes the tag for every file at once, so anything older is dead weight.
/** @type {Map<string, {body: Buffer, gz: Buffer|null}>} */
const MODULE_CACHE = new Map();
let moduleCacheTag = null;

/**
 * Answer one `.js` of the served runtime with its import specifiers versioned (`servesVersionedModule` decided
 * that). Mirrors serveFile's headers and 304 handling; the ETag carries the tag, since the body depends on it.
 * @returns {Promise<boolean>} false when the file cannot be read (the caller falls back to serveFile)
 */
async function serveVersionedModule(req, res, absPath, stat, tag, mountName, segments, query, log) {
  const key = `${absPath}\0${stat.size}\0${Math.floor(stat.mtimeMs)}\0${tag}`;
  let entry = MODULE_CACHE.get(key);
  if (!entry) {
    let raw;
    try { raw = await fsp.readFile(absPath, 'utf8'); } catch { return false; }
    entry = { body: Buffer.from(versionModuleJs(raw, tag), 'utf8'), gz: null };
    if (moduleCacheTag !== tag) { MODULE_CACHE.clear(); moduleCacheTag = tag; }
    MODULE_CACHE.set(key, entry);
  }
  const useGzip = stat.size >= GZIP_MIN_BYTES && acceptsGzip(req.headers['accept-encoding']);
  const baseTag = `${stat.size.toString(16)}-${Math.floor(stat.mtimeMs).toString(16)}-v${tag}`;
  const etag = `"${baseTag}${useGzip ? '-gz' : ''}"`;
  const headers = {
    'Content-Type': MIME['.js'],
    'Cache-Control': cacheControlFor('.js', mountName, segments, query),
    ETag: etag,
    'Last-Modified': stat.mtime.toUTCString(),
    Vary: 'Accept-Encoding',
  };
  if (isNotModified(req, etag, stat.mtime)) { res.writeHead(304, headers); res.end(); return true; }
  let body = entry.body;
  if (useGzip) {
    if (!entry.gz) entry.gz = await gzipAsync(entry.body, { level: 6 });
    body = entry.gz;
    headers['Content-Encoding'] = 'gzip';
  }
  headers['Content-Length'] = body.length;
  res.writeHead(200, headers);
  res.end(req.method === 'HEAD' ? undefined : body);
  void log;
  return true;
}

// ---------------------------------------------------------------------------------------------------
// index.html: stamp the build tag onto its own asset references
// ---------------------------------------------------------------------------------------------------

// The 25 /css/…, /js/… and /vendor/… references in public/index.html carry no content hash, so files.js
// cacheControlFor() can only answer `no-cache` for them — a returning player revalidates every one, and the
// 4-hour Cloudflare rule is all that stands between a page load and this host's uplink. `?v=<build>` lands on the
// IMMUTABLE_CACHE branch instead (files.js), so a repeat visit downloads nothing at all.
//
// The tag is the served runtime's own hash (http/buildTag.js), so a deploy bumps every reference by itself:
// there is no version constant anyone can forget to raise. Only `index.html` is rewritten, and only in memory —
// the file on disk stays byte-for-byte what was shipped.
// Matches the same paths wherever they appear: `href="/css/…"`, `"/js/…"` in the importmap's JSON, and
// `"preact": "/vendor/preact.module.js"` — a bare `/vendor/…` that is not a reference is left alone only
// because the prefix list is exact (nothing else in the document starts with those four directories).
const VERSIONED_REF = /(")(\/(?:css|js|vendor|i18n)\/[^"]*?)(")/g;

/**
 * `index.html` with `?v=<buildTag>` on its own asset references.
 * @param {Buffer|string} raw
 * @param {string} tag
 * @returns {string}
 */
export function versionIndexHtml(raw, tag) {
  const body = typeof raw === 'string' ? raw : raw.toString('utf8');
  if (!tag) return body;
  return body.replace(VERSIONED_REF, (m, open, url, close) => {
    if (/[?&]v=/.test(url)) return m; // already versioned: never double-stamp
    return `${open}${url}${/[?&]/.test(url) ? '&' : '?'}v=${tag}${close}`;
  });
}

/**
 * Answer `index.html` with its asset references versioned (null when the file cannot be read).
 * @returns {Promise<boolean>} false → the caller falls back to serveFile
 */
async function serveVersionedIndex(req, res, absPath, stat, tag, log) {
  if (!tag) return false;
  let raw;
  try { raw = await fsp.readFile(absPath, 'utf8'); } catch { return false; }
  const body = Buffer.from(versionIndexHtml(raw, tag), 'utf8');
  const headers = {
    'Content-Type': `${MIME['.html'] || 'text/html'}; charset=utf-8`,
    'Cache-Control': 'no-cache', // the entry document always revalidates: it is what carries the new tag
    ETag: `"${stat.size.toString(16)}-${Math.floor(stat.mtimeMs).toString(16)}-${tag}"`,
    'Last-Modified': stat.mtime.toUTCString(),
  };
  if (isNotModified(req, headers.ETag, stat.mtime)) { res.writeHead(304, headers); res.end(); return true; }
  headers['Content-Length'] = body.length;
  res.writeHead(200, headers);
  res.end(req.method === 'HEAD' ? undefined : body);
  void log;
  return true;
}

/**
 * Create the static request handler.
 * @param {{ publicDir: string, dataDir: string, sharedDir: string, simDir?: string, packsDir?: string,
 *   packs?: ReturnType<typeof createPackRegistry>, log?: object }} dirs
 *   packs: the server's pack registry (default: one over publicDir, dataDir and packsDir — ROOT/packs)
 * @returns {(req: import('node:http').IncomingMessage, res: import('node:http').ServerResponse, rawPath: string, query: string) => Promise<void>}
 */
export function createStaticHandler({ publicDir, dataDir, sharedDir, simDir = path.join(ROOT, 'server', 'sim'), packsDir = path.join(ROOT, 'packs'), packs = null, log = noopLog }) {
  const registry = packs || createPackRegistry({ publicDir, dataDir, packsDir }, { log: /** @type {any} */ (log) });
  const mounts = [
    { prefix: '/data/', name: 'data', dir: path.resolve(dataDir) },
    { prefix: '/shared/', name: 'shared', dir: path.resolve(sharedDir) },
    // the simulation: ES modules only (no directory listings, no other file types, no Node-only loader)
    { prefix: '/sim/', name: 'sim', dir: path.resolve(simDir), only: new Set(['.js']), deny: SIM_PRIVATE },
    { prefix: '/', name: 'public', dir: path.resolve(publicDir) },
  ];
  const shimBody = Buffer.from(DATA_SHIM_JS);
  const shimTag = `"shim-${shimBody.length.toString(16)}"`;
  const gzipCache = new GzipCache();
  // 素材 CDN (SP_ASSET_CDN): '' unless the deployment sets it — read once, a change needs a restart
  const artCdn = normalizeAssetCdn(process.env.SP_ASSET_CDN, log);

  return async function serveStatic(req, res, rawPath, query) {
    let decoded;
    try { decoded = decodeURIComponent(rawPath); } catch { sendError(req, res, 400, '请求地址无效 · Bad request'); return; }
    if (!decoded.startsWith('/') || decoded.includes('\0') || decoded.includes('\\')) {
      sendError(req, res, 400, '请求地址无效 · Bad request');
      return;
    }
    if (decoded === '/data.js') {
      const headers = { 'Content-Type': MIME['.js'], 'Cache-Control': 'no-cache', ETag: shimTag, 'Content-Length': shimBody.length };
      if (isNotModified(req, shimTag, new Date(0))) { delete headers['Content-Length']; res.writeHead(304, headers); res.end(); return; }
      res.writeHead(200, headers);
      res.end(req.method === 'HEAD' ? undefined : shimBody);
      return;
    }
    // Content packs (server/packs.js): the live index, and only the files a pack's manifest names
    if (decoded.startsWith(PACKS_URL)) {
      const parts = decoded.slice(PACKS_URL.length).split('/');
      if (parts.length === 1 && parts[0] === PACK_INDEX_FILE) { sendJson(req, res, 200, registry.index()); return; }
      const abs = parts.length >= 2 && !parts.some((s) => s === '' || s === '.' || s === '..') ? registry.servable(parts[0], parts.slice(1).join('/')) : null;
      const st = abs ? await fsp.stat(abs).catch(() => null) : null;
      if (!st || !st.isFile()) { sendError(req, res, 404, '页面不存在 · Not found', decoded.length <= 200 ? decoded : ''); return; }
      await serveFile(req, res, abs, st, 'packs', parts, query, gzipCache, log);
      return;
    }
    // Extension-less audio (download-manager avoidance): /media/bgm/act1 → /assets/audio/bgm/act1.mp3
    if (decoded.startsWith(MEDIA_PREFIX)) {
      await serveMedia(req, res, decoded.slice(MEDIA_PREFIX.length), query, publicDir, gzipCache, log);
      return;
    }
    // Bare mount paths (e.g. "/data") → treat as the mount directory.
    const mount = mounts.find((m) => decoded.startsWith(m.prefix) || decoded === m.prefix.slice(0, -1)) || mounts[mounts.length - 1];
    const rest = decoded.length > mount.prefix.length ? decoded.slice(mount.prefix.length) : '';
    const segments = rest.split('/').filter((s) => s.length > 0);
    if (segments.some((s) => s === '..' || s === '.')) { sendError(req, res, 403, '禁止访问 · Forbidden'); return; }
    // 素材 CDN (SP_ASSET_CDN): anything still addressed to the local art or font tree is handed to the CDN. The three
    // manifests already carry absolute URLs, so this covers what they do not: index.html links /fonts/fonts.css
    // directly, and a client that kept an old manifest would ask for /assets/… again. A deployment can therefore ship
    // with no public/assets and no public/fonts at all. 302 (not a proxy): the point is that this host carries none of
    // the bytes. Short max-age — the redirect target is stable, but a CDN change should take effect without a restart.
    if (artCdn && (segments[0] === 'assets' || segments[0] === 'fonts')) {
      res.writeHead(302, { Location: `${artCdn}${segments.join('/')}`, 'Cache-Control': 'public, max-age=300' });
      res.end();
      return;
    }
    if (segments.some((s) => s.startsWith('.'))) { sendError(req, res, 404, '页面不存在 · Not found'); return; }
    if (mount.only && (!segments.length || !mount.only.has(path.extname(segments[segments.length - 1]).toLowerCase())
      // (case-insensitive: the host may be Windows / macOS, where NODEDATA.JS opens nodeData.js)
      || (mount.deny && mount.deny.has(segments[segments.length - 1].toLowerCase())))) {
      sendError(req, res, 404, '页面不存在 · Not found');
      return;
    }
    let absPath = path.join(mount.dir, ...segments);
    if (absPath !== mount.dir && !absPath.startsWith(mount.dir + path.sep)) { sendError(req, res, 403, '禁止访问 · Forbidden'); return; }

    let stat;
    let viaDirectory = false;
    try {
      stat = await fsp.stat(absPath);
      if (stat.isDirectory()) {
        if (!decoded.endsWith('/')) {
          // Built from normalized segments (never from the raw path) so "//host" can't become an open redirect.
          const loc = (mount.prefix + segments.map(encodeURIComponent).join('/') + '/').replace(/\/{2,}/g, '/');
          res.writeHead(301, { Location: loc + (query ? `?${query}` : ''), 'Cache-Control': 'no-cache', 'Content-Length': 0 });
          res.end();
          return;
        }
        absPath = path.join(absPath, 'index.html');
        segments.push('index.html');
        viaDirectory = true;
        stat = await fsp.stat(absPath);
      }
      // Not a regular file, or a file addressed like a directory ("/app.js/") → 404.
      if (!stat.isFile() || (decoded.endsWith('/') && !viaDirectory)) {
        throw Object.assign(new Error('not a file'), { code: 'ENOENT' });
      }
      if (mount.deny) {
        // the on-disk name decides (case-insensitive file systems, Windows 8.3 short names like NODEDA~1.JS)
        const real = await fsp.realpath(absPath);
        if (mount.deny.has(path.basename(real).toLowerCase())) throw Object.assign(new Error('private'), { code: 'ENOENT' });
      }
    } catch (e) {
      if (e && e.code === 'ENOENT' && mount.name === 'data' && segments.length === 1 && segments[0] === LOCAL_ART_MANIFEST) {
        // Optional local-client art (DESIGN §13): an install without it gets an empty manifest instead of a 404,
        // so browsers don't log an error on every page load. Clients treat empty groups as "no local art".
        res.writeHead(200, { 'Content-Type': MIME['.json'], 'Cache-Control': 'no-cache', 'Content-Length': EMPTY_LOCAL_ART.length });
        res.end(req.method === 'HEAD' ? undefined : EMPTY_LOCAL_ART);
      } else if (e && (e.code === 'ENOENT' || e.code === 'ENOTDIR' || e.code === 'EISDIR' || e.code === 'ENAMETOOLONG')) {
        sendError(req, res, 404, '页面不存在 · Not found', decoded.length <= 200 ? decoded : '');
      } else if (e && (e.code === 'EACCES' || e.code === 'EPERM')) {
        sendError(req, res, 403, '禁止访问 · Forbidden');
      } else {
        log.error('[http] stat failed', e);
        sendError(req, res, 500, '服务器内部错误 · Internal error');
      }
      return;
    }
    // index.html: stamp ?v=<build> onto its own asset references so a repeat visit downloads nothing
    if (mount.name === 'public' && segments.length === 1 && segments[0] === 'index.html') {
      const tag = buildTag();
      if (await serveVersionedIndex(req, res, absPath, stat, tag, log)) return;
    }
    // the module graph below it: stamp ?v=<build> onto the imports inside each served module.
    // A range request is left to serveFile: it asks for the file's own bytes (offset-addressed), not for the
    // rewritten response, and browsers never range a module — only downloads and <audio> do.
    if (!req.headers.range && servesVersionedModule(path.extname(absPath).toLowerCase(), mount.name, segments)) {
      const tag = buildTag();
      if (tag && await serveVersionedModule(req, res, absPath, stat, tag, mount.name, segments, query, log)) return;
    }
    // 素材 CDN (SP_ASSET_CDN): the art manifests leave with absolute CDN URLs, the file on disk stays untouched
    if (artCdn && mount.name === 'data' && segments.length === 1 && CDN_ART_MANIFESTS.has(segments[0])) {
      if (await serveArtManifest(req, res, absPath, stat, artCdn, log)) return;
    }
    await serveFile(req, res, absPath, stat, mount.name, segments, query, gzipCache, log);
  };
}
