plugins {
    id 'com.android.application'
}

android {
    namespace 'icu.jiangjiangze.stronghold'
    compileSdk 34
    ndkVersion '26.3.11579264'

    defaultConfig {
        applicationId 'icu.jiangjiangze.stronghold'
        minSdk 26
        targetSdk 34
        versionCode 4
        versionName '2.2.0'
        buildConfigField 'String', 'EMBEDDED_APP_VERSION', '"0.1.0"'
        buildConfigField 'String', 'DEFAULT_ORIGIN', '"https://stronghold.jiangjiangze.icu"'
        buildConfigField 'String', 'UPSTREAM_RELEASE_API', '"https://api.github.com/repos/sganggs/Stronghold-Protocol/releases/latest"'
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    signingConfigs {
        release {
            storeFile file('../stronghold.keystore')
            storePassword 'stronghold2026'
            keyAlias 'stronghold'
            keyPassword 'stronghold2026'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    buildFeatures {
        buildConfig true
    }

    androidResources {
        noCompress 'png', 'jpg', 'jpeg', 'webp', 'avif', 'gif', 'ogg', 'oga', 'opus', 'mp3', 'wav', 'm4a', 'aac', 'woff2', 'skel', 'bin', 'wasm', 'so'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
            version '3.22.1'
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}
